### ISSUE TITLE
Please do not steal our code

### ISSUE THREAD

**Issue by photopea** [NFXT/Photopea-Desktop-App#1]
I see that you have copied the content of our software Photopea.com. You have modified our code, removed our advertisement and made other Premium features availabe for free.

I would like to ask you to take it down. If everyone cracked our software like you do, we would not be able to make any money, and Photopea would not exist today.

**Comment by DUOLabs333** [comment]
Shame that they didn't respond to you, and I have nothing but respect for you and you product. However, how is this any different than someone manually downloading the site and modifying it themselves? It's client-side, so this can certainly happen. Are you OK if I host just the `Updater.py` script with none of the actual files?

**Comment by photopea** [comment]
@DUOLabs333 We make money by asking people to watch ads, or pay for the Premium account.

If you are helping people get a version of Photopea, where they dont need to do any of that, it hurts our business :(

Are you trying to make people pay you for using Photopea, or see your ads instead of our? If not, how is your version different from what people can get by pressing More - Install Photopea at www.Photopea.com (which also works offline)?

**Comment by DUOLabs333** [comment]
I will never show ads (especially since I don't actually host a website running the code)? As far as I know, the "Install" button, does not actually work offline -- ie, you can't load it up completely disconnected from the internet. You have to be connected to the internet to at least load it up, and not everything downloads at load.

**Comment by photopea** [comment]
It is enough to open www.Photopea.com at least once in your life. Since then, it is cached by a browser forever.

You can turn off your laptop, go far far away from any wifi, turn on your laptop, open a browser, enter www.Photopea.com and it will work.

**Comment by DUOLabs333** [comment]
If this is about ads, then if you use it offline, people won't see ads regardless. However, I understand what you are trying to say (of course, for those that clear their cache regularly, it won't help much).

**Comment by NFXT** [comment]
@photopea sorry, I haven't checked my email in a while/or github
I didn't touch any of your code, the desktop app is based purely on @DUOLabs333's offline photopea.

Also, as @DUOLabs333 said, your offline app wont work if a person clears his/her cache every time which is something I do, hence why I decided to contribute to his cause.
Besides the point, but you do realize how many people use adblockers nowadays? People are already benefitting from some of your "premium features" without paying.
Maybe you should consider writing a copyright policy to make it clear to everyone, not to redistribute or repackage your software? Either way, I truly appreciate this marvel work of yours and hope you all the best. I'm making this repo private. I apologize for any inconvenience caused. Thank you.

**Comment by DUOLabs333** [comment]
@photopea We can continue this conversation in my repo if you want.
